exclude = [
  "@ref",
  "@cite",
  "^https://github.com/.*/releases/tag/v.*$",
  "^https://doi.org/FIXME$",
  "^https://singularitti.github.io/VASP.jl/stable$",
  "^https://blog.esciencecenter.nl", # due to a certificate error (cf. #556)
  "zenodo.org/badge/DOI/FIXME$"
]

exclude_path = [
  "docs/build"
]
