name = "VASP"
uuid = "77813d3a-3836-5367-9172-6187308da7ae"
version = "0.1.0"
authors = ["singularitti <singularitti@outlook.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
EnumX = "4e289a0a-7415-4d19-859d-a7e5c4648b56"
FileTrees = "72696420-646e-6120-6e77-6f6420746567"
Glob = "c27321d9-0574-5035-807b-f59d2c89b15c"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
DataFrames = "1.8.1"
EnumX = "1.0.6"
FileTrees = "0.3.10"
Glob = "1.4.0"
PythonCall = "0.9.31"
julia = "1.10"
