name = "VASP"
uuid = "77813d3a-3836-5367-9172-6187308da7ae"
version = "0.1.0"
authors = ["singularitti <singularitti@outlook.com>"]

[workspace]
projects = ["test", "docs"]

[deps]
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
PythonCall = "0.9.31"
julia = "1.10"
