[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LiveServer = "16fef848-5104-11e9-1b77-fb7a48bbb589"
VASP = "77813d3a-3836-5367-9172-6187308da7ae"

[compat]
Documenter = "1"

[sources]
VASP = {path = ".."}
